apiVersion: v2
type: application
name: origin-ca-issuer
version: 0.7.0
appVersion: 0.13.0
description: A Helm chart for origin-ca-issuer
home: https://github.com/mislavperi/origin-ca-issuer
maintainers:
- name: mislavperi
keywords:
- cert-manager
- cloudflare
- tls
sources:
- https://github.com/mislavperi/origin-ca-issuer
